@startuml C3_Ahorcado
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/java.puml
!include DEVICONS/msql_server.puml
!include FONTAWESOME/server.puml

AddElementTag("backendContainer", $fontColor=$ELEMENT_FONT_COLOR, $bgColor="#335DA5", $shape=EightSidedShape(), $legendText="backend container\neight sided")

Container(consola, "Consola", "Interfaz de Usuario", "Interfaz de línea de comandos para ingresar letras")
Container(interfaz, "Interfaz", "Programado en java", "Interfaz de línea de comandos para interactuar con el juego")
    Container(backend, "Aplicacion", "Java, Docker Container", "Proporciona funcionalidad a travez de la API", $tags="backendContainer", $sprite="java")

ContainerDb(mysql, "Base de Datos", "MySQL", "Almacena los datos del juego en MySQL", $sprite="msql_server")
ContainerDb(sqlite, "Base de Datos", "SQLite", "Almacena los datos del juego en SQLite", "server")

System(ventana, "Seleccion de la DB", "El sistema pregunta con una ventana que base de datos utilizar")

Rel(consola, interfaz, "El usuario ingresa a la interface del juego mediante la consola")
Rel(interfaz, backend, "La interface despliega el juego mediante el codigo en java")
Rel_Neighbor(backend, ventana, "Seleccion de la base de datos")
Rel(ventana, mysql, "Seleccion de MySQL")
Rel(ventana, sqlite, "Seleccion de SQLite")

@enduml
