@startuml AhorcadoC4
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(player, "Jugador", "El usuario que juega al ahorcado")

package "Capa de Presentación" as PRESENTACION {
  component UI as "Interfaz de Usuario"
  component Tablero as "Tablero"
  note right of Tablero: Implementa un Observer para actualizar el estado del juego
  note left of Tablero: Usa observer

  component Jugador as "Jugador"
  note right of Jugador: Usa el Observer para notificar cambios
}

package "Capa de Negocio" as NEGOCIO {
  component LogDb as "LogDb"
  note right: Gestiona la selección de la base de datos y la comunicación con la capa DAO
}

package "Capa de Persistencia (DAO)" as DAO {
  component DB as "DB"

  package DBFACTORY as "Factory"

  component JMYSQL as "MySQL"
  note right: Implementación MySQL

  component JSQLITE as "SQLite"
  note right: Implementación SQLite
}

Rel(player, UI, "Interactúa con")
Rel(UI, Tablero, "Controla el juego")
Rel(Jugador, Tablero, "Notifica cambios (Observer)")
Rel(Tablero, LogDb, "Avisa cambios y accede a la bd")
Rel(LogDb, DB, "Guarda y recupera datos")
Rel(DB, DBFACTORY, "Selecciona la base de datos (Singlenton)")
Rel(DBFACTORY, JMYSQL, "Crea instancia de MySQL")
Rel(DBFACTORY, JSQLITE, "Crea instancia de SQLite")

@enduml
